/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';
import {
  AdRoute,
} from './components/common/interface/common.interface';


export namespace Components {

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AdCssAnimation {}
  interface AdCssAnimationAttributes extends StencilHTMLAttributes {}

  interface AdJsAnimation {}
  interface AdJsAnimationAttributes extends StencilHTMLAttributes {}

  interface AdSettings {}
  interface AdSettingsAttributes extends StencilHTMLAttributes {}

  interface AdSvgAnimation {}
  interface AdSvgAnimationAttributes extends StencilHTMLAttributes {}

  interface AdTransition {}
  interface AdTransitionAttributes extends StencilHTMLAttributes {}

  interface AdIconSettings {}
  interface AdIconSettingsAttributes extends StencilHTMLAttributes {}

  interface AdSidebar {
    'list': AdRoute[];
  }
  interface AdSidebarAttributes extends StencilHTMLAttributes {
    'list'?: AdRoute[];
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'AdCssAnimation': Components.AdCssAnimation;
    'AdJsAnimation': Components.AdJsAnimation;
    'AdSettings': Components.AdSettings;
    'AdSvgAnimation': Components.AdSvgAnimation;
    'AdTransition': Components.AdTransition;
    'AdIconSettings': Components.AdIconSettings;
    'AdSidebar': Components.AdSidebar;
  }

  interface StencilIntrinsicElements {
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'ad-css-animation': Components.AdCssAnimationAttributes;
    'ad-js-animation': Components.AdJsAnimationAttributes;
    'ad-settings': Components.AdSettingsAttributes;
    'ad-svg-animation': Components.AdSvgAnimationAttributes;
    'ad-transition': Components.AdTransitionAttributes;
    'ad-icon-settings': Components.AdIconSettingsAttributes;
    'ad-sidebar': Components.AdSidebarAttributes;
  }


  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAdCssAnimationElement extends Components.AdCssAnimation, HTMLStencilElement {}
  var HTMLAdCssAnimationElement: {
    prototype: HTMLAdCssAnimationElement;
    new (): HTMLAdCssAnimationElement;
  };

  interface HTMLAdJsAnimationElement extends Components.AdJsAnimation, HTMLStencilElement {}
  var HTMLAdJsAnimationElement: {
    prototype: HTMLAdJsAnimationElement;
    new (): HTMLAdJsAnimationElement;
  };

  interface HTMLAdSettingsElement extends Components.AdSettings, HTMLStencilElement {}
  var HTMLAdSettingsElement: {
    prototype: HTMLAdSettingsElement;
    new (): HTMLAdSettingsElement;
  };

  interface HTMLAdSvgAnimationElement extends Components.AdSvgAnimation, HTMLStencilElement {}
  var HTMLAdSvgAnimationElement: {
    prototype: HTMLAdSvgAnimationElement;
    new (): HTMLAdSvgAnimationElement;
  };

  interface HTMLAdTransitionElement extends Components.AdTransition, HTMLStencilElement {}
  var HTMLAdTransitionElement: {
    prototype: HTMLAdTransitionElement;
    new (): HTMLAdTransitionElement;
  };

  interface HTMLAdIconSettingsElement extends Components.AdIconSettings, HTMLStencilElement {}
  var HTMLAdIconSettingsElement: {
    prototype: HTMLAdIconSettingsElement;
    new (): HTMLAdIconSettingsElement;
  };

  interface HTMLAdSidebarElement extends Components.AdSidebar, HTMLStencilElement {}
  var HTMLAdSidebarElement: {
    prototype: HTMLAdSidebarElement;
    new (): HTMLAdSidebarElement;
  };

  interface HTMLElementTagNameMap {
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'ad-css-animation': HTMLAdCssAnimationElement
    'ad-js-animation': HTMLAdJsAnimationElement
    'ad-settings': HTMLAdSettingsElement
    'ad-svg-animation': HTMLAdSvgAnimationElement
    'ad-transition': HTMLAdTransitionElement
    'ad-icon-settings': HTMLAdIconSettingsElement
    'ad-sidebar': HTMLAdSidebarElement
  }

  interface ElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'ad-css-animation': HTMLAdCssAnimationElement;
    'ad-js-animation': HTMLAdJsAnimationElement;
    'ad-settings': HTMLAdSettingsElement;
    'ad-svg-animation': HTMLAdSvgAnimationElement;
    'ad-transition': HTMLAdTransitionElement;
    'ad-icon-settings': HTMLAdIconSettingsElement;
    'ad-sidebar': HTMLAdSidebarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
